# Generated by Django 5.2.8 on 2025-12-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upi_app',
            field=models.CharField(blank=True, help_text='GPay / PhonePe / Paytm', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_txn',
            field=models.CharField(blank=True, help_text='Simulated UPI Transaction ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card (Simulated)'), ('crypto', 'Cryptocurrency'), ('upi', 'UPI')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
