# Generated by Django 5.2.8 on 2026-01-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='productcomment',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
