# Generated by Django 5.2.8 on 2026-02-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_productcomment_options_productcomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
